### ISSUE TITLE
set up code coverage

### ISSUE THREAD

**Issue by Laci135** [BME-MIT-IET/csv-szindikatus-iet-2020#15]
Jacoco + codecov.io have been set up, using the Travis CI pipeline. -- Laci135

**Comment by Laci135** [comment]
Jacoco + codecov.io have been set up, using the Travis CI pipeline. -- Laci135

**Comment by cynolterm** [comment]
Code coverage has been set up and is working fine.

**Comment by Laci135** [comment]
Pull request:
https://github.com/BME-MIT-IET/csv-szindikatus-iet-2020/pull/9
